using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Turnkey.code
{
    public class CountryCode
    {

        public static readonly CountryCode AF = new CountryCode("AF");// Afghanistan
        public static readonly CountryCode AX = new CountryCode("AX"); // Åland Islands
        public static readonly CountryCode AL = new CountryCode("AL"); // Albania
        public static readonly CountryCode DZ = new CountryCode("DZ"); // Algeria
        public static readonly CountryCode AS = new CountryCode("AS"); // American Samoa
        public static readonly CountryCode AD = new CountryCode("AD"); // Andorra
        public static readonly CountryCode AO = new CountryCode("AO"); // Angola
        public static readonly CountryCode AI = new CountryCode("AI"); // Anguilla
        public static readonly CountryCode AQ = new CountryCode("AQ"); // Antarctica
        public static readonly CountryCode AG = new CountryCode("AG"); // Antigua and Barbuda
        public static readonly CountryCode AR = new CountryCode("AR"); // Argentina
        public static readonly CountryCode AM = new CountryCode("AM"); // Armenia
        public static readonly CountryCode AW = new CountryCode("AW"); // Aruba
        public static readonly CountryCode AU = new CountryCode("AU"); // Australia
        public static readonly CountryCode AT = new CountryCode("AT"); // Austria
        public static readonly CountryCode AZ = new CountryCode("AZ"); // Azerbaijan
        public static readonly CountryCode BS = new CountryCode("BS"); // Bahamas
        public static readonly CountryCode BH = new CountryCode("BH"); // Bahrain
        public static readonly CountryCode BD = new CountryCode("BD"); // Bangladesh
        public static readonly CountryCode BB = new CountryCode("BB"); // Barbados
        public static readonly CountryCode BY = new CountryCode("BY"); // Belarus
        public static readonly CountryCode BE = new CountryCode("BE"); // Belgium
        public static readonly CountryCode BZ = new CountryCode("BZ"); // Belize
        public static readonly CountryCode BJ = new CountryCode("BJ"); // Benin
        public static readonly CountryCode BM = new CountryCode("BM"); // Bermuda
        public static readonly CountryCode BT = new CountryCode("BT"); // Bhutan
        public static readonly CountryCode BO = new CountryCode("BO"); // Bolivia (Plurinational State of Bolivia)
        public static readonly CountryCode BQ = new CountryCode("BQ"); // Bonaire (Sint Eustatius and Saba)
        public static readonly CountryCode BA = new CountryCode("BA"); // Bosnia and Herzegovina
        public static readonly CountryCode BW = new CountryCode("BW"); // Botswana
        public static readonly CountryCode BV = new CountryCode("BV"); // Bouvet Island
        public static readonly CountryCode BR = new CountryCode("BR"); // Brazil
        public static readonly CountryCode IO = new CountryCode("IO"); // British Indian Ocean Territory
        public static readonly CountryCode BN = new CountryCode("BN"); // Brunei Darussalam
        public static readonly CountryCode BG = new CountryCode("BG"); // Bulgaria
        public static readonly CountryCode BF = new CountryCode("BF"); // Burkina Faso
        public static readonly CountryCode BI = new CountryCode("BI"); // Burundi
        public static readonly CountryCode KH = new CountryCode("KH"); // Cambodia
        public static readonly CountryCode CM = new CountryCode("CM"); // Cameroon
        public static readonly CountryCode CA = new CountryCode("CA"); // Canada
        public static readonly CountryCode CV = new CountryCode("CV"); // Cabo Verde
        public static readonly CountryCode KY = new CountryCode("KY"); // Cayman Islands
        public static readonly CountryCode CF = new CountryCode("CF"); // Central African Republic
        public static readonly CountryCode TD = new CountryCode("TD"); // Chad
        public static readonly CountryCode CL = new CountryCode("CL"); // Chile
        public static readonly CountryCode CN = new CountryCode("CN"); // China
        public static readonly CountryCode CX = new CountryCode("CX"); // Christmas Island
        public static readonly CountryCode CC = new CountryCode("CC"); // Cocos (Keeling) Islands
        public static readonly CountryCode CO = new CountryCode("CO"); // Colombia
        public static readonly CountryCode KM = new CountryCode("KM"); // Comoros
        public static readonly CountryCode CG = new CountryCode("CG"); // Congo
        public static readonly CountryCode CD = new CountryCode("CD"); // Congo (Democratic Republic of the Congo)
        public static readonly CountryCode CK = new CountryCode("CK"); // Cook Islands
        public static readonly CountryCode CR = new CountryCode("CR"); // Costa Rica
        public static readonly CountryCode CI = new CountryCode("CI"); // Côte d'Ivoire
        public static readonly CountryCode HR = new CountryCode("HR"); // Croatia
        public static readonly CountryCode CU = new CountryCode("CU"); // Cuba
        public static readonly CountryCode CW = new CountryCode("CW"); // Curaçao
        public static readonly CountryCode CY = new CountryCode("CY"); // Cyprus
        public static readonly CountryCode CZ = new CountryCode("CZ"); // Czech Republic
        public static readonly CountryCode DK = new CountryCode("DK"); // Denmark
        public static readonly CountryCode DJ = new CountryCode("DJ"); // Djibouti
        public static readonly CountryCode DM = new CountryCode("DM"); // Dominica
        public static readonly CountryCode DO = new CountryCode("DO"); // Dominican Republic
        public static readonly CountryCode EC = new CountryCode("EC"); // Ecuador
        public static readonly CountryCode EG = new CountryCode("EG"); // Egypt
        public static readonly CountryCode SV = new CountryCode("SV"); // El Salvador
        public static readonly CountryCode GQ = new CountryCode("GQ"); // Equatorial Guinea
        public static readonly CountryCode ER = new CountryCode("ER"); // Eritrea
        public static readonly CountryCode EE = new CountryCode("EE"); // Estonia
        public static readonly CountryCode ET = new CountryCode("ET"); // Ethiopia
        public static readonly CountryCode FK = new CountryCode("FK"); // Falkland Islands (Malvinas)
        public static readonly CountryCode FO = new CountryCode("FO"); // Faroe Islands
        public static readonly CountryCode FJ = new CountryCode("FJ"); // Fiji
        public static readonly CountryCode FI = new CountryCode("FI"); // Finland
        public static readonly CountryCode FR = new CountryCode("FR"); // France
        public static readonly CountryCode GF = new CountryCode("GF"); // French Guiana
        public static readonly CountryCode PF = new CountryCode("PF"); // French Polynesia
        public static readonly CountryCode TF = new CountryCode("TF"); // French Southern Territories
        public static readonly CountryCode GA = new CountryCode("GA"); // Gabon
        public static readonly CountryCode GM = new CountryCode("GM"); // Gambia
        public static readonly CountryCode GE = new CountryCode("GE"); // Georgia
        public static readonly CountryCode DE = new CountryCode("DE"); // Germany
        public static readonly CountryCode GH = new CountryCode("GH"); // Ghana
        public static readonly CountryCode GI = new CountryCode("GI"); // Gibraltar
        public static readonly CountryCode GR = new CountryCode("GR"); // Greece
        public static readonly CountryCode GL = new CountryCode("GL"); // Greenland
        public static readonly CountryCode GD = new CountryCode("GD"); // Grenada
        public static readonly CountryCode GP = new CountryCode("GP"); // Guadeloupe
        public static readonly CountryCode GU = new CountryCode("GU"); // Guam
        public static readonly CountryCode GT = new CountryCode("GT"); // Guatemala
        public static readonly CountryCode GG = new CountryCode("GG"); // Guernsey
        public static readonly CountryCode GN = new CountryCode("GN"); // Guinea
        public static readonly CountryCode GW = new CountryCode("GW"); // Guinea-Bissau
        public static readonly CountryCode GY = new CountryCode("GY"); // Guyana
        public static readonly CountryCode HT = new CountryCode("HT"); // Haiti
        public static readonly CountryCode HM = new CountryCode("HM"); // Heard Island and McDonald Islands
        public static readonly CountryCode VA = new CountryCode("VA"); // Holy See
        public static readonly CountryCode HN = new CountryCode("HN"); // Honduras
        public static readonly CountryCode HK = new CountryCode("HK"); // Hong Kong
        public static readonly CountryCode HU = new CountryCode("HU"); // Hungary
        public static readonly CountryCode IS = new CountryCode("IS"); // Iceland
        public static readonly CountryCode IN = new CountryCode("IN"); // India
        public static readonly CountryCode ID = new CountryCode("ID"); // Indonesia
        public static readonly CountryCode IR = new CountryCode("IR"); // Iran (Islamic Republic of Iran)
        public static readonly CountryCode IQ = new CountryCode("IQ"); // Iraq
        public static readonly CountryCode IE = new CountryCode("IE"); // Ireland
        public static readonly CountryCode IM = new CountryCode("IM"); // Isle of Man
        public static readonly CountryCode IL = new CountryCode("IL"); // Israel
        public static readonly CountryCode IT = new CountryCode("IT"); // Italy
        public static readonly CountryCode JM = new CountryCode("JM"); // Jamaica
        public static readonly CountryCode JP = new CountryCode("JP"); // Japan
        public static readonly CountryCode JE = new CountryCode("JE"); // Jersey
        public static readonly CountryCode JO = new CountryCode("JO"); // Jordan
        public static readonly CountryCode KZ = new CountryCode("KZ"); // Kazakhstan
        public static readonly CountryCode KE = new CountryCode("KE"); // Kenya
        public static readonly CountryCode KI = new CountryCode("KI"); // Kiribati
        public static readonly CountryCode KP = new CountryCode("KP"); // Korea (Democratic People's Republic of Korea)
        public static readonly CountryCode KR = new CountryCode("KR"); // Korea (Republic of Korea)
        public static readonly CountryCode KW = new CountryCode("KW"); // Kuwait
        public static readonly CountryCode KG = new CountryCode("KG"); // Kyrgyzstan
        public static readonly CountryCode LA = new CountryCode("LA"); // Lao People's Democratic Republic
        public static readonly CountryCode LV = new CountryCode("LV"); // Latvia
        public static readonly CountryCode LB = new CountryCode("LB"); // Lebanon
        public static readonly CountryCode LS = new CountryCode("LS"); // Lesotho
        public static readonly CountryCode LR = new CountryCode("LR"); // Liberia
        public static readonly CountryCode LY = new CountryCode("LY"); // Libya
        public static readonly CountryCode LI = new CountryCode("LI"); // Liechtenstein
        public static readonly CountryCode LT = new CountryCode("LT"); // Lithuania
        public static readonly CountryCode LU = new CountryCode("LU"); // Luxembourg
        public static readonly CountryCode MO = new CountryCode("MO"); // Macao
        public static readonly CountryCode MK = new CountryCode("MK"); // Macedonia (the former Yugoslav Republic of Macedonia)
        public static readonly CountryCode MG = new CountryCode("MG"); // Madagascar
        public static readonly CountryCode MW = new CountryCode("MW"); // Malawi
        public static readonly CountryCode MY = new CountryCode("MY"); // Malaysia
        public static readonly CountryCode MV = new CountryCode("MV"); // Maldives
        public static readonly CountryCode ML = new CountryCode("ML"); // Mali
        public static readonly CountryCode MT = new CountryCode("MT"); // Malta
        public static readonly CountryCode MH = new CountryCode("MH"); // Marshall Islands
        public static readonly CountryCode MQ = new CountryCode("MQ"); // Martinique
        public static readonly CountryCode MR = new CountryCode("MR"); // Mauritania
        public static readonly CountryCode MU = new CountryCode("MU"); // Mauritius
        public static readonly CountryCode YT = new CountryCode("YT"); // Mayotte
        public static readonly CountryCode MX = new CountryCode("MX"); // Mexico
        public static readonly CountryCode FM = new CountryCode("FM"); // Micronesia (Federated States of Micronesia)
        public static readonly CountryCode MD = new CountryCode("MD"); // Moldova (Republic of Moldova)
        public static readonly CountryCode MC = new CountryCode("MC"); // Monaco
        public static readonly CountryCode MN = new CountryCode("MN"); // Mongolia
        public static readonly CountryCode ME = new CountryCode("ME"); // Montenegro
        public static readonly CountryCode MS = new CountryCode("MS"); // Montserrat
        public static readonly CountryCode MA = new CountryCode("MA"); // Morocco
        public static readonly CountryCode MZ = new CountryCode("MZ"); // Mozambique
        public static readonly CountryCode MM = new CountryCode("MM"); // Myanmar
        public static readonly CountryCode NA = new CountryCode("NA"); // Namibia
        public static readonly CountryCode NR = new CountryCode("NR"); // Nauru
        public static readonly CountryCode NP = new CountryCode("NP"); // Nepal
        public static readonly CountryCode NL = new CountryCode("NL"); // Netherlands
        public static readonly CountryCode NC = new CountryCode("NC"); // New Caledonia
        public static readonly CountryCode NZ = new CountryCode("NZ"); // New Zealand
        public static readonly CountryCode NI = new CountryCode("NI"); // Nicaragua
        public static readonly CountryCode NE = new CountryCode("NE"); // Niger
        public static readonly CountryCode NG = new CountryCode("NG"); // Nigeria
        public static readonly CountryCode NU = new CountryCode("NU"); // Niue
        public static readonly CountryCode NF = new CountryCode("NF"); // Norfolk Island
        public static readonly CountryCode MP = new CountryCode("MP"); // Northern Mariana Islands
        public static readonly CountryCode NO = new CountryCode("NO"); // Norway
        public static readonly CountryCode OM = new CountryCode("OM"); // Oman
        public static readonly CountryCode PK = new CountryCode("PK"); // Pakistan
        public static readonly CountryCode PW = new CountryCode("PW"); // Palau
        public static readonly CountryCode PS = new CountryCode("PS"); // Palestine (State of Palestine)
        public static readonly CountryCode PA = new CountryCode("PA"); // Panama
        public static readonly CountryCode PG = new CountryCode("PG"); // Papua New Guinea
        public static readonly CountryCode PY = new CountryCode("PY"); // Paraguay
        public static readonly CountryCode PE = new CountryCode("PE"); // Peru
        public static readonly CountryCode PH = new CountryCode("PH"); // Philippines
        public static readonly CountryCode PN = new CountryCode("PN"); // Pitcairn
        public static readonly CountryCode PL = new CountryCode("PL"); // Poland
        public static readonly CountryCode PT = new CountryCode("PT"); // Portugal
        public static readonly CountryCode PR = new CountryCode("PR"); // Puerto Rico
        public static readonly CountryCode QA = new CountryCode("QA"); // Qatar
        public static readonly CountryCode RE = new CountryCode("RE"); // Réunion
        public static readonly CountryCode RO = new CountryCode("RO"); // Romania
        public static readonly CountryCode RU = new CountryCode("RU"); // Russian Federation
        public static readonly CountryCode RW = new CountryCode("RW"); // Rwanda
        public static readonly CountryCode BL = new CountryCode("BL"); // Saint Barthélemy
        public static readonly CountryCode SH = new CountryCode("SH"); // Saint Helena (Ascension and Tristan da Cunha)
        public static readonly CountryCode KN = new CountryCode("KN"); // Saint Kitts and Nevis
        public static readonly CountryCode LC = new CountryCode("LC"); // Saint Lucia
        public static readonly CountryCode MF = new CountryCode("MF"); // Saint Martin (French part)
        public static readonly CountryCode PM = new CountryCode("PM"); // Saint Pierre and Miquelon
        public static readonly CountryCode VC = new CountryCode("VC"); // Saint Vincent and the Grenadines
        public static readonly CountryCode WS = new CountryCode("WS"); // Samoa
        public static readonly CountryCode SM = new CountryCode("SM"); // San Marino
        public static readonly CountryCode ST = new CountryCode("ST"); // Sao Tome and Principe
        public static readonly CountryCode SA = new CountryCode("SA"); // Saudi Arabia
        public static readonly CountryCode SN = new CountryCode("SN"); // Senegal
        public static readonly CountryCode RS = new CountryCode("RS"); // Serbia
        public static readonly CountryCode SC = new CountryCode("SC"); // Seychelles
        public static readonly CountryCode SL = new CountryCode("SL"); // Sierra Leone
        public static readonly CountryCode SG = new CountryCode("SG"); // Singapore
        public static readonly CountryCode SX = new CountryCode("SX"); // Sint Maarten (Dutch part)
        public static readonly CountryCode SK = new CountryCode("SK"); // Slovakia
        public static readonly CountryCode SI = new CountryCode("SI"); // Slovenia
        public static readonly CountryCode SB = new CountryCode("SB"); // Solomon Islands
        public static readonly CountryCode SO = new CountryCode("SO"); // Somalia
        public static readonly CountryCode ZA = new CountryCode("ZA"); // South Africa
        public static readonly CountryCode GS = new CountryCode("GS"); // South Georgia and the South Sandwich Islands
        public static readonly CountryCode SS = new CountryCode("SS"); // South Sudan
        public static readonly CountryCode ES = new CountryCode("ES"); // Spain
        public static readonly CountryCode LK = new CountryCode("LK"); // Sri Lanka
        public static readonly CountryCode SD = new CountryCode("SD"); // Sudan
        public static readonly CountryCode SR = new CountryCode("SR"); // Suriname
        public static readonly CountryCode SJ = new CountryCode("SJ"); // Svalbard and Jan Mayen
        public static readonly CountryCode SZ = new CountryCode("SZ"); // Swaziland
        public static readonly CountryCode SE = new CountryCode("SE"); // Sweden
        public static readonly CountryCode CH = new CountryCode("CH"); // Switzerland
        public static readonly CountryCode SY = new CountryCode("SY"); // Syrian Arab Republic
        public static readonly CountryCode TW = new CountryCode("TW"); // Taiwan
        public static readonly CountryCode TJ = new CountryCode("TJ"); // Tajikistan
        public static readonly CountryCode TZ = new CountryCode("TZ"); // Tanzania (United Republic of Tanzania)
        public static readonly CountryCode TH = new CountryCode("TH"); // Thailand
        public static readonly CountryCode TL = new CountryCode("TL"); // Timor-Leste
        public static readonly CountryCode TG = new CountryCode("TG"); // Togo
        public static readonly CountryCode TK = new CountryCode("TK"); // Tokelau
        public static readonly CountryCode TO = new CountryCode("TO"); // Tonga
        public static readonly CountryCode TT = new CountryCode("TT"); // Trinidad and Tobago
        public static readonly CountryCode TN = new CountryCode("TN"); // Tunisia
        public static readonly CountryCode TR = new CountryCode("TR"); // Turkey
        public static readonly CountryCode TM = new CountryCode("TM"); // Turkmenistan
        public static readonly CountryCode TC = new CountryCode("TC"); // Turks and Caicos Islands
        public static readonly CountryCode TV = new CountryCode("TV"); // Tuvalu
        public static readonly CountryCode UG = new CountryCode("UG"); // Uganda
        public static readonly CountryCode UA = new CountryCode("UA"); // Ukraine
        public static readonly CountryCode AE = new CountryCode("AE"); // United Arab Emirates
        public static readonly CountryCode GB = new CountryCode("GB"); // United Kingdom of Great Britain and Northern Ireland
        public static readonly CountryCode US = new CountryCode("US"); // United States of America
        public static readonly CountryCode UM = new CountryCode("UM"); // United States Minor Outlying Islands
        public static readonly CountryCode UY = new CountryCode("UY"); // Uruguay
        public static readonly CountryCode UZ = new CountryCode("UZ"); // Uzbekistan
        public static readonly CountryCode VU = new CountryCode("VU"); // Vanuatu
        public static readonly CountryCode VE = new CountryCode("VE"); // Venezuela (Bolivarian Republic of Venezuela)
        public static readonly CountryCode VN = new CountryCode("VN"); // Viet Nam
        public static readonly CountryCode VG = new CountryCode("VG"); // Virgin Islands (British)
        public static readonly CountryCode VI = new CountryCode("VI"); // Virgin Islands (U.S.)
        public static readonly CountryCode WF = new CountryCode("WF"); // Wallis and Futuna
        public static readonly CountryCode EH = new CountryCode("EH"); // Western Sahara
        public static readonly CountryCode YE = new CountryCode("YE"); // Yemen
        public static readonly CountryCode ZM = new CountryCode("ZM"); // Zambia
        public static readonly CountryCode ZW = new CountryCode("ZW"); // Zimbabwe

        private readonly String code;

        public CountryCode(String code)
        {
            this.code = code;
        }

        public String GetCode()
        {
            return code;
        }

    }
}